language: node_js
node_js:
  - 8
branches:
  only:
  - master
services:
  - redis-server
env:
  global:
    - "REDIS_URL=redis://localhost:6379"
cache:
  directories:
  - $HOME/.npm
install:
- npm i
sudo: required
after_success: npx codecov --file=./coverage/lcov.info
script: npm run test-all

before_install:
  - npm i -g npm@5.10
  - npm --version